import {chromium,devices} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {SAVE_KEY,validSave} from '../game-shell.js';
const base=process.env.WATER_URL||'http://127.0.0.1:5191/';
const mobileOnly=process.argv.includes('--mobile-only');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-webgpu']});
const report={},errors=[];
const ready=async p=>{p.on('pageerror',e=>errors.push(String(e)));await p.goto(base);await p.waitForFunction(()=>waterDiagnostics.ready||waterDiagnostics.errors.length,null,{timeout:240000});assert.deepEqual(await p.evaluate(()=>waterDiagnostics.errors),[]);};
const settled=p=>p.waitForFunction(()=>!waterLab.sessionState().shell.pending&&!waterLab.sessionState().shell.saveBusy);
const state=p=>p.evaluate(()=>waterLab.combatState());
const fixture=(p,config)=>p.evaluate(c=>waterLab.combatFixture(c),config);
const step=(p,frames,dt,input={})=>p.evaluate(({frames,dt,input})=>waterLab.combatAdvance(frames,dt,{simulationOnly:true,...input}),{frames,dt,input});
const shield=(data,i=0)=>data[(32+i*32+14)*4+1];
const hull=(data,i=0)=>data[(32+i*32+14)*4];
const activeRounds=data=>Array.from({length:64},(_,i)=>256*4+i*16).filter(j=>data[j+3]>0);
async function launch(p){await p.locator('#newGame').click();await settled(p);await p.locator('#pilotName').fill('Sam');await p.locator('#newShipName').fill('Horizon Runner');await p.locator('#launchFlight').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');await p.keyboard.press('Escape');await settled(p);}
const shotScenario=(position=[0,0,-120],health=[90,60,20,0])=>({enemies:[{position,health}],player:[100,75,20,0],velocity:[0,0,0]});
try{
 await mkdir('captures/combat',{recursive:true});
 if(!mobileOnly){
 const context=await browser.newContext({viewport:{width:2560,height:1440},deviceScaleFactor:1}),p=await context.newPage();await ready(p);console.log('COMBAT GPU READY');report.geometry=await p.evaluate(()=>waterLab.shipGeometry());assert.equal(report.geometry.symmetryError,0);assert.ok(report.geometry.finite&&report.geometry.triangles>60000);report.rays=await p.evaluate(()=>waterLab.shipRayTest());assert.ok(report.rays.maxError<.002);await launch(p);await p.evaluate(()=>waterLab.shipAltitude(300));
 const mounts=await p.evaluate(()=>waterLab.weaponGeometry());
 // Stop time but keep the real HUD visible; deterministic steps dispatch the production CUDA kernel.
 await p.locator('#resumeGame').click();await fixture(p,shotScenario());
 let data=await step(p,1,.02,{weapon:1,fire:true});assert.equal(shield(data),44,'Instant laser must apply damage on the firing tick');assert.equal(data[41],1);report.laser={instantShieldDamage:16,beamPool:true};const laserStart=data.slice(544*4,544*4+3),emitter=mounts[laserStart[0]<0?79:127];assert.ok(Math.abs(laserStart[0]-(emitter.lo[0]+emitter.hi[0])/2)<.01);assert.ok(Math.abs(laserStart[2]-emitter.lo[2]+.02)<.01);
 await p.screenshot({path:'captures/combat/laser-1440p.png'});
 await fixture(p,shotScenario());data=await step(p,1,.02,{weapon:0,fire:true});assert.equal(shield(data),60,'A bullet must travel before applying damage');assert.equal(activeRounds(data).length,1);const bulletStart=data.slice(activeRounds(data)[0],activeRounds(data)[0]+3),gun=mounts[bulletStart[0]<0?47:95];assert.ok(Math.abs(bulletStart[0]-(gun.lo[0]+gun.hi[0])/2)<.01);assert.ok(Math.abs(bulletStart[1]-(gun.lo[1]+gun.hi[1])/2)<.01);assert.ok(Math.abs(bulletStart[2]-gun.lo[2]+.04)<.01);report.weaponMounts={bulletAperture:true};data=await step(p,15,.01);assert.equal(shield(data),52);report.bullets={delayedDamage:8};
 await fixture(p,shotScenario([0,0,-50]));await step(p,1,.1,{weapon:0,fire:true});data=await step(p,1,.1);assert.equal(shield(data),52,'100 m bullet step must hit the target between endpoints');report.bullets.sweptCollision=true;
 // Independent relative-motion oracle: inherited lateral speed cancels the moving origin once.
 await fixture(p,{...shotScenario([0,0,-1000]),velocity:[250,0,0]});data=await step(p,1,.1,{weapon:0,fire:true});const j=activeRounds(data)[0],a=data.slice(j,j+3);data=await step(p,1,.1);const b=data.slice(j,j+3);assert.ok(Math.abs(b[0]-a[0])<.01,`Unexpected lateral drift: ${b[0]-a[0]}`);assert.ok(Math.abs(Math.hypot(...b.map((v,i)=>v-a[i]))-100)<.1);report.bullets.inheritedMotion=true;
 await fixture(p,shotScenario([35,0,-150]));data=await step(p,1,.02,{weapon:2,fire:true});assert.equal(data[42],1);assert.equal(data[10],3);assert.equal(shield(data),60);const rocket=activeRounds(data)[0],initial=data.slice(rocket+4,rocket+7),rocketStart=data.slice(rocket,rocket+3),tubeIndex=(rocketStart[0]<0?73:121)+(Math.abs(rocketStart[0])>6.2?1:0),tube=mounts[tubeIndex];assert.ok(Math.abs(rocketStart[0]-(tube.lo[0]+tube.hi[0])/2)<.01);assert.ok(Math.abs(rocketStart[2]-tube.lo[2]+.04)<.01);report.weaponMounts.laserAndRocketApertures=true;
 await fixture(p,{enemies:[{position:[-30,25,-170]}],clear:false});data=await step(p,10,.02);const turned=data.slice(rocket+4,rocket+7);assert.ok(turned[0]<initial[0]&&turned[1]>initial[1],'Rocket must turn toward the moved target');data=await step(p,160,.01);assert.ok(shield(data)<=12.01,'Homing rocket must hit moved target');report.rockets={autoTarget:true,turning:true,damage:48};
 await fixture(p,{...shotScenario(),enemies:[]});data=await step(p,5,.1,{weapon:2,fire:true});assert.equal(activeRounds(data).length,0);assert.equal(data[10],4);report.rockets.noTargetDoesNotSpendAmmo=true;
 await fixture(p,shotScenario([0,0,-120],[90,4,0,0]));data=await step(p,1,.02,{weapon:1,fire:true});assert.equal(shield(data),0);assert.equal(hull(data),78);report.shieldAbsorption=true;
 await fixture(p,{...shotScenario([0,0,-200],[50,0,0,0]),player:[60,0,0,0]});data=await step(p,39,.1);assert.equal(data[5],0);assert.equal(shield(data),0);data=await step(p,20,.1);assert.ok(data[5]>20&&data[5]<25);assert.equal(data[4],60);assert.equal(hull(data),50);data=await step(p,61,.1);assert.equal(data[5],75);assert.equal(shield(data),60);assert.ok(data[4]>63&&data[4]<65);assert.ok(hull(data)>53&&hull(data)<55);report.regeneration={delayedShields:true,delayedHull:true,playerAndEnemies:true};
 await fixture(p,shotScenario([0,0,-120],[2,0,0,0]));const kills=(await state(p)).data[15];data=await step(p,1,.02,{weapon:1,fire:true});assert.equal(data[7],0);assert.equal(data[15],kills+1);assert.ok(Array.from({length:16},(_,i)=>544*4+i*16).some(j=>data[j+3]>0&&data[j+7]===2));report.enemyDestruction=true;console.log('WEAPONS AND REPAIR PASSED');
 // Pause preserves the encounter, while names/colours and combat vitals persist.
 await fixture(p,{...shotScenario(),player:[82,31,0,0]});await p.keyboard.press('Escape');await settled(p);const before=(await state(p)).data;await p.waitForTimeout(350);const after=(await state(p)).data;assert.equal(after[0],before[0]);assert.deepEqual(after.slice(128,768),before.slice(128,768));const save=JSON.parse(await p.evaluate(key=>localStorage.getItem(key),SAVE_KEY));assert.ok(validSave(save));assert.equal(save.ship[56],82);assert.equal(save.ship[57],31);report.pauseAndSave=true;
 await p.locator('#resumeGame').click();await fixture(p,{...shotScenario(),player:[0,0,0,1]});await p.waitForFunction(()=>waterLab.sessionState().shell.page==='defeat');assert.deepEqual(JSON.parse(await p.evaluate(key=>localStorage.getItem(key),SAVE_KEY)),save);await p.screenshot({path:'captures/combat/recovery.png'});await p.locator('#recoverCraft').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');await p.keyboard.press('Escape');await settled(p);let recovered=await state(p);assert.equal(recovered.ship[56],100);assert.equal(recovered.ship[57],75);assert.equal(recovered.ship[62],4);report.recovery={fullHealth:true,lastCheckpointPreserved:true};
 // Run the actual enemy AI with its initial grace period, not a fixture.
 await p.locator('#resumeGame').click();data=await step(p,300,.1);assert.ok(data[4]<100||data[5]<75,'Enemies must attack the player');assert.ok(data.every(Number.isFinite));report.enemyAI={attacks:true,finite:true};await p.keyboard.press('Escape');await settled(p);
 // A paused fixture makes performance and image comparisons use identical scenes.
 if((await p.evaluate(()=>waterLab.sessionState())).shell.page==='defeat'){await p.locator('#recoverCraft').click();await p.keyboard.press('Escape');await settled(p);}
 await p.locator('#resumeGame').click();await fixture(p,{enemies:[{position:[0,4,-70]},{position:[-40,20,-120]},{position:[75,45,-190]}],player:[100,75,20,0],velocity:[0,0,0]});data=await step(p,1,.02,{weapon:1,fire:true});await p.screenshot({path:'captures/combat/combat-1440p.png'});
 report.performance1440=await p.evaluate(()=>waterLab.combatCost(20));
 await p.setViewportSize({width:3840,height:2160});await p.locator('#quality').evaluate(el=>{el.value='3840';el.dispatchEvent(new Event('change',{bubbles:true}));});await p.waitForFunction(()=>waterDiagnostics.width===3840);await p.evaluate(()=>waterLab.combatAdvance(1,0));await p.screenshot({path:'captures/combat/combat-4k.png'});report.performance4k=await p.evaluate(()=>waterLab.combatCost(20));
 // Inspect actual hardware and canopy in a controlled daylight ocean view.
 await p.evaluate(async()=>{document.getElementById('depthMode').value='0';document.getElementById('depth').value='8';document.getElementById('weatherMode').value='0';await waterLab.shipAltitude(15);await waterLab.shipView(2.65,.32,22);});
 await p.screenshot({path:'captures/combat/near-plane-laser-4k.png'});
 await fixture(p,{enemies:[],player:[100,75,20,0],velocity:[0,0,0]});
 await p.screenshot({path:'captures/combat/armed-craft-4k.png'});await p.screenshot({path:'captures/combat/armed-craft-detail.png',clip:{x:1000,y:580,width:1840,height:1170}});
 for(const [name,yaw,elevation] of [['side',1.57,.08],['front-level',3.14,.02],['underside',2.65,-.12]]){await p.evaluate(({yaw,elevation})=>waterLab.shipView(yaw,elevation,22),{yaw,elevation});await p.screenshot({path:`captures/combat/joins-${name}.png`,clip:{x:1000,y:580,width:1840,height:1170}});}
 await p.evaluate(()=>waterLab.shipView(.42,.42,22));await p.screenshot({path:'captures/combat/canopy-and-hardpoints.png',clip:{x:1000,y:580,width:1840,height:1170}});
 // Actual keyboard firing and camera steering through the game input path.
 await p.keyboard.press('KeyV');await fixture(p,{enemies:[{position:[0,3,-120]}],player:[100,75,20,0],velocity:[0,0,0]});await p.keyboard.press('Digit1');await p.evaluate(()=>waterLab.resume());await p.keyboard.down('KeyF');await p.waitForTimeout(400);await p.keyboard.up('KeyF');await p.evaluate(()=>waterLab.pause());assert.ok((await state(p)).data[40]>=1);report.keyboardFire=true;
 assert.deepEqual(await p.evaluate(()=>waterDiagnostics.errors),[]);await p.keyboard.press('Escape');await settled(p);await p.locator('#returnMain').click();await settled(p);const savedBeforeFree=await p.evaluate(key=>localStorage.getItem(key),SAVE_KEY);await p.locator('#freeRoam').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');assert.equal(await p.locator('#combatHUD').isVisible(),false);assert.equal((await state(p)).active,false);assert.equal(await p.evaluate(key=>localStorage.getItem(key),SAVE_KEY),savedBeforeFree);report.freeRoamIsolated=true;
 await context.close();console.log('DESKTOP COMBAT PASSED');
 await writeFile('captures/combat/desktop-validation.json',JSON.stringify(report,null,2));
 }
 const phone=await browser.newContext({...devices['Pixel 7'],viewport:{width:393,height:852}}),q=await phone.newPage();await ready(q);await launch(q);await q.locator('#resumeGame').click();await fixture(q,shotScenario());assert.ok(await q.locator('#fireWeapon').isVisible());await q.locator('[data-weapon="2"]').click();assert.equal(await q.locator('#weaponName').textContent(),'HOMING ROCKETS');await q.screenshot({path:'captures/combat/phone-portrait.png'});
 const fireBox=await q.locator('#fireWeapon').boundingBox();await q.evaluate(()=>waterLab.resume());const cdp=await phone.newCDPSession(q);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:fireBox.x+fireBox.width/2,y:fireBox.y+fireBox.height/2,id:1}]});await q.waitForTimeout(250);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await q.evaluate(()=>waterLab.pause());assert.ok((await state(q)).data[42]>=1,'Held touch Fire must launch a rocket');
 // Releasing a second finger on the steering pad must not cancel held Fire.
 await fixture(q,shotScenario([0,0,-1000]));await q.locator('[data-weapon="0"]').click();const stickBox=await q.locator('#moveStick').boundingBox(),firePoint={x:fireBox.x+fireBox.width/2,y:fireBox.y+fireBox.height/2,id:1},stickPoint={x:stickBox.x+stickBox.width/2,y:stickBox.y+stickBox.height/2,id:2};
 await q.evaluate(()=>{window.combatTouchAudit=[];addEventListener('pointerup',e=>combatTouchAudit.push(e.target.id));waterLab.resume();});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[firePoint,stickPoint]});await q.waitForTimeout(250);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[stickPoint]});await q.waitForFunction(()=>combatTouchAudit.includes('moveStick'),null,{timeout:2000});
 const heldShots=(await state(q)).data[40];await q.waitForTimeout(400);assert.ok((await state(q)).data[40]>heldShots,'Fire must continue after releasing the steering finger');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const releasedShots=(await state(q)).data[40];await q.waitForTimeout(250);assert.equal((await state(q)).data[40],releasedShots,'Releasing Fire must stop shooting');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[firePoint]});await q.waitForTimeout(150);await q.evaluate(()=>dispatchEvent(new Event('blur')));const blurredShots=(await state(q)).data[40];await q.waitForTimeout(250);assert.equal((await state(q)).data[40],blurredShots,'Losing focus must stop shooting');assert.equal(await q.locator('#fireWeapon').evaluate(el=>el.classList.contains('firing')),false);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await q.evaluate(()=>waterLab.pause());
 await q.setViewportSize({width:852,height:393});await q.waitForTimeout(100);await q.screenshot({path:'captures/combat/phone-landscape.png'});assert.equal(await q.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const [inspect,full]=await Promise.all(['#shipInspect','#fullscreen'].map(id=>q.locator(id).boundingBox()));assert.ok(inspect.x+inspect.width<=full.x||full.x+full.width<=inspect.x||inspect.y+inspect.height<=full.y||full.y+full.height<=inspect.y,'Landscape controls must not overlap');assert.deepEqual(await q.evaluate(()=>waterDiagnostics.errors),[]);report.mobile={actualMobileGPUProfile:true,touchFire:true,multiTouchFire:true,releaseAndBlurStopFire:true,weaponSelection:true,physicalPhone:false};await phone.close();
 assert.deepEqual(errors,[]);await writeFile(`captures/combat/${mobileOnly?'mobile-validation':'validation'}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
