import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {SAVE_KEY,validSave} from '../game-shell.js';
const browser=process.env.CONNECT?await chromium.connectOverCDP('http://127.0.0.1:9321'):await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-webgpu','--remote-debugging-port=9321']});
const errors=[],report={};const p=process.env.CONNECT?browser.contexts()[0].pages()[0]:await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(String(e)));
const state=()=>p.evaluate(()=>waterLab.outpostState());
const step=(frames=1,dt=.05,input={})=>p.evaluate(({frames,dt,input})=>waterLab.outpostAdvance(frames,dt,input),{frames,dt,input});
const command=c=>p.evaluate(c=>waterLab.outpostCommand(c),c);
const fixture=c=>p.evaluate(c=>waterLab.outpostFixture(c),c);
const pause=()=>p.evaluate(()=>waterLab.pause());
const combat=()=>p.evaluate(()=>waterLab.combatState());
const tick=(frames=1,input={})=>p.evaluate(({frames,input})=>waterLab.combatAdvance(frames,.1,{simulationOnly:true,...input}),{frames,input});
const settled=()=>p.waitForFunction(()=>!waterLab.sessionState().shell.pending&&!waterLab.sessionState().shell.saveBusy);
const shot=name=>p.screenshot({path:`captures/outpost/${name}.png`});
try{
 await mkdir('captures/outpost',{recursive:true});await p.setViewportSize({width:1600,height:1000});if(process.env.REUSE){await p.evaluate(()=>waterLab.reloadKernels(['outpost_step']));if((await p.evaluate(()=>waterLab.sessionState())).shell.page==='playing')await p.keyboard.press('Escape');await p.locator('#returnMain').click();await settled();}else{await p.addInitScript(()=>localStorage.removeItem('clearwater6.1.save.v1'));await p.goto(process.env.WATER_URL||'http://127.0.0.1:5191/');}await p.waitForFunction(()=>waterDiagnostics.ready||waterDiagnostics.errors.length,null,{timeout:480000});assert.deepEqual(await p.evaluate(()=>waterDiagnostics.errors),[]);console.log('READY');
 await p.locator('#newGame').click();await settled();await p.locator('#pilotName').fill('Sam');await p.locator('#newShipName').fill('Horizon Runner');await p.locator('#launchFlight').click();if(process.env.REUSE)await p.locator('#confirmNewGame').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');await pause();
 let initial=await state(),s=initial.ship;assert.equal(s[84],2);assert.equal(s[87],62);assert.equal((await combat()).data[7],0);await shot('arrival');
 s=await command(2);assert.equal(s[84],3);await shot('disembark');const parked=await state();s=await step(40,.05,{keys:['KeyW']});assert.ok(s[98]<parked.ship[98]-7);assert.deepEqual((await state()).navigation,parked.navigation);assert.deepEqual(s.slice(0,8),parked.ship.slice(0,8));assert.equal(s[91],2);await shot('meet-commander');
 await command(2);assert.equal((await state()).ship[152],2);assert.ok(await p.locator('#outpostDialogue').isVisible());await shot('dialogue');const frozen=(await state()).ship;s=await step(20,.05,{keys:['KeyW']});assert.deepEqual(s.slice(96,100),frozen.slice(96,100));
 await p.getByRole('button',{name:'I’ll defend the outpost.'}).click();await p.waitForFunction(()=>waterDiagnostics.outpost?.stage===1);await pause();s=(await state()).ship;assert.equal(s[85],1);report.dialogue={proximity:true,freezesWalking:true,acceptsContract:true};
 // Crew and building collision: diagonal movement cannot walk through the commander.
 const nearCrew=await state();s=await step(80,.05,{keys:['KeyW']});assert.ok(s[98]>-18,'Commander must block the pilot');await fixture({restore:nearCrew});
 s=await step(40,.05,{keys:['KeyS']});assert.equal(s[91],1);s=await command(2);assert.equal(s[84],2);s=await command(1);assert.equal(s[84],4);s=await step(41,.05);assert.equal(s[84],0);assert.equal(s[85],2);await shot('launch');report.surface={landedStart:true,firstPerson:true,walkedMetres:7.6,shipStayedParked:true,crewCollision:true,boarded:true,tookOff:true};
 // Reject an unsafe landing while preserving the active flight state.
 const airborne=await state();await fixture({fields:{9:[0,0,-50,50],1:[0,0,0,50]}});s=await command(1);assert.equal(s[84],0);assert.equal(s[90],3);await fixture({restore:airborne});await p.evaluate(h=>waterLab.shipAltitude(h),airborne.ship[1]+90);s=await command(1);assert.equal(s[84],0);assert.equal(s[90],4);await fixture({restore:airborne});report.landingRejects={fast:true,high:true};
 // Run countdown at a modest resolution. Rendering is verified separately at 2K/4K.
 await p.locator('#quality').evaluate(el=>{el.value='768';el.dispatchEvent(new Event('change'));});s=await step(125,.1);assert.equal(s[85],3);assert.equal((await combat()).data[7],3);await shot('first-wave');
 // Aim through flight controls and fire actual mounted lasers at moving AI.
 async function destroyWing(){let shots=0;for(let attempt=0;attempt<100;attempt++){let c=await combat();const data=c.data;const target=Array.from({length:5},(_,i)=>32+i*32).find(e=>data[e*4+3]>0&&data[(e+14)*4]>0);if(target===undefined)return shots;const rel=data.slice((target+9)*4,(target+9)*4+3);const yaw=Math.atan2(rel[0],-rel[2]),pitch=Math.atan2(rel[1],Math.hypot(rel[0],rel[2]));const ship=c.ship;await step(1,0,{lookX:Math.atan2(Math.sin(yaw-ship[4]),Math.cos(yaw-ship[4])),lookY:pitch-ship[5]});await tick(3,{weapon:1,fire:true});shots++;}throw Error('Wing did not clear with actual lasers');}
 report.firstWingShots=await destroyWing();s=(await state()).ship;assert.equal(s[85],4);assert.equal(s[136],0);s=await step(82,.1);assert.equal(s[85],5);assert.equal((await combat()).data[7],4);report.secondWingShots=await destroyWing();s=(await state()).ship;assert.equal(s[85],6);assert.equal(s[64],7);assert.ok(s[132]>0);report.combat={twoWings:true,actualMountedLasers:true,kills:s[64],outpostSurvived:s[132]};
 // No implicit victory when flying away; saved remaining wing is restored.
 const victory=await state();await fixture({fields:{21:[0,3,0,62],34:[2,0,0,0],27:[0,-1,0,0]},clearCombat:true});assert.equal((await combat()).data[7],2);await tick(400);s=(await state()).ship;assert.equal(s[85],3);assert.equal(s[136],2);assert.ok(s[132]<1500||s[133]<500);report.baseUnderAttack=true;
 await fixture({fields:{33:[0,0,0,1]}});await tick(1);assert.equal((await state()).ship[85],8);report.failure=true;await fixture({restore:victory,clearCombat:true});
 // Return over the same pad, land using real L control, walk back to the crew.
 const current=(await state()).ship;await fixture({fields:{1:[0,0,0,0],8:[0,0,0,0],9:[0,0,0,0]}});s=await command(1);assert.equal(s[84],1);s=await step(40,.05);assert.equal(s[84],2);s=await command(2);s=await step(40,.05,{keys:['KeyW']});assert.equal(s[91],2);await command(2);await command(4);await pause();s=(await state()).ship;assert.equal(s[85],7);assert.equal(s[108],750);await command(4);assert.equal((await state()).ship[108],750);report.rewardOnce=true;
 // Save via the real pause menu, then Continue without reloading pipelines.
 await p.keyboard.press('Escape');await settled();const save=JSON.parse(await p.evaluate(k=>localStorage.getItem(k),SAVE_KEY));assert.ok(validSave(save));assert.equal(save.ship[108],750);assert.equal(save.ship[84],3);await p.locator('#returnMain').click();await settled();await p.locator('#continueGame').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');await pause();s=(await state()).ship;assert.equal(s[108],750);assert.equal(s[85],7);assert.equal(s[84],3);assert.ok(Math.abs(s[96]-save.ship[96])<.02&&Math.abs(s[98]-save.ship[98])<.02);report.saveContinue=true;
 // Ground service and a landing on terrain beyond the constructed pad.
 const finished=await state();s=await step(65,.05,{keys:['KeyD']});assert.equal(s[91],3);await fixture({fields:{14:[20,0,0,0],15:[0,0,0,0]}});await command(2);await command(5);await pause();s=(await state()).ship;assert.equal(s[56],100);assert.equal(s[57],75);assert.equal(s[62],4);report.engineerService=true;
 await fixture({fields:{21:[0,7,0,62],0:[s[0],s[1]+30,s[2],1],1:[0,0,0,0],8:[0,0,0,0]}});s=await step(100,.1,{keys:['KeyW']});s=await step(45,.1,{keys:['KeyS']});assert.ok(s[131]>400);s=await command(1);assert.equal(s[84],1);s=await step(50,.1);assert.equal(s[84],2);s=await command(2);assert.equal(s[84],3);const terrain=await state();s=await step(12,.05,{keys:['KeyD']});assert.ok(s[96]>terrain.ship[96]+1);report.landedAndWalkedOnTerrain=true;await fixture({restore:finished,clearCombat:true});
 // Ground-level PC quality captures and honest GPU timing boundaries.
 await p.setViewportSize({width:2560,height:1440});await p.locator('#quality').evaluate(el=>{el.value='2560';el.dispatchEvent(new Event('change'));});await step(1,0);await shot('outpost-1440p');report.performance1440=await p.evaluate(()=>waterLab.benchmark(16));
 await p.setViewportSize({width:3840,height:2160});await p.locator('#quality').evaluate(el=>{el.value='3840';el.dispatchEvent(new Event('change'));});await step(1,0);await shot('outpost-4k');report.performance4k=await p.evaluate(()=>waterLab.benchmark(16));
 // Keep the underlying CUDA flight refactor's existing geometry oracle.
 report.shipRays=await p.evaluate(()=>waterLab.shipRayTest());await p.keyboard.press('Escape');await settled();await p.locator('#returnMain').click();await settled();const normalSave=await p.evaluate(k=>localStorage.getItem(k),SAVE_KEY);await p.locator('#freeRoam').click();await p.waitForFunction(()=>waterLab.sessionState().shell.page==='playing');await pause();s=await command(1);assert.equal(s[84],0);assert.equal(s[90],1);report.waterLandingRejected=true;await step(25,.1);assert.equal((await combat()).active,false);assert.equal((await state()).ship[85],0);assert.equal(await p.evaluate(k=>localStorage.getItem(k),SAVE_KEY),normalSave);report.freeRoamPreservesSave=true;await p.keyboard.press('Escape');
 assert.ok((await state()).ship.every(Number.isFinite));assert.deepEqual(errors,[]);assert.deepEqual(await p.evaluate(()=>waterDiagnostics.errors),[]);report.errors=errors;await writeFile('captures/outpost/validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){await writeFile('captures/outpost/partial-validation.json',JSON.stringify(report,null,2));console.error(error);await p.screenshot({path:'captures/outpost/failure.png'}).catch(()=>{});await writeFile('captures/outpost/failure.json',JSON.stringify({message:String(error),state:await state().catch(()=>null),diagnostics:await p.evaluate(()=>waterDiagnostics).catch(()=>null)},null,2));if(process.env.KEEP_BROWSER)await new Promise(()=>{});throw error;}finally{await browser.close();}
